name: First Workflow
on: workflow_dispatch

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First-Step
        run: echo "This is the first step."

      - name: Second-Step
        run: echo "This is the second step."

      - name: Third-Step
        run: echo "This is the third step."

      - name: Fourth-Step
        run: echo "Done with all steps."

  
  Second-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Fifth-Step
        run: echo "This is the fifth step."

      - name: Sixth-Step
        run: echo "This is the sixth step."

      - name: Seventh-Step
        run: echo "This is the seventh step."

      - name: Eighth-Step
        run: echo "Done with all steps."
